services:
  image-processing:
    image: 'image-processing:latest'
    depends_on:
      - rabbitmq
      - image-processing-worker
      - files
    build:
      context: ./
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8024:80
    networks:
      - image-processing-net

  rabbitmq:
    image: rabbitmq:4.1.1-management
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 15672:15672
    networks:
      - image-processing-net

  image-processing-worker:
    image: 'image-processing-worker:latest'
    restart: always
    build:
      context: ./
    depends_on:
      - rabbitmq
      - files
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: ["python", "-u", "./scripts/tasks_worker.py"]
    networks:
      - image-processing-net

  files:
    image: files:latest
    depends_on:
      - postgres
    volumes:
      - ./file_storage:/file_storage
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - 8023:80
    networks:
      - image-processing-net

  postgres:
    image: postgres:17-bookworm
    volumes:
      - test_pgdata:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5434:5432
    networks:
      - image-processing-net

networks:
  image-processing-net:
    name: image-processing-net

volumes:
  test_pgdata: